### ISSUE TITLE
Page Loading Animation

### ISSUE THREAD

**Issue by coffeepanda** [Trikolon/liquidradio#11]

**Comment by Trikolon** [comment]
I don't think that a loading animation is needed. The application loads fast enough.
I've already made it so that the raw vuejs code isn't showing but instead it waits for the dom-link to be ready and then shows the content.
Also, on mobile platform, when you add it to your homescreen it displays a splash screen until it's loaded. If we add another artificial loading screen we'd have two on this platform.
